



export  const Data = [
    {
      id: 1,
      title: "Nigerian maths prodigy, Faith Odunsi, shines on the global stage",
      Name: "Good News",
      Description: "Fifteen-year-old Faith Odunsi recently made Nigeria proud as she emerged the Global Open Mathematics Tournament winner, an international competition with participants from Europe, Africa, America, Asia, and Australia. ",
      url: "https://res.cloudinary.com/dmsyfdo0y/image/upload/v1631574368/News%20Article%20Images/Education_2_ns7tlh.png",
  
      contents: [`Fifteen-year-old Faith Odunsi recently made Nigeria proud as she emerged the Global Open Mathematics Tournament winner, an international competition with participants from Europe, Africa, America, Asia, and Australian`, <br />, <br />, `Odunsi, an SS3 student from Ijebu in Ogun state, shared her experience winning the global competition in an interview with The Punch.`, `She disclosed that winning the 'tough competition' made her happy and honored. Odunsi also narrated how she excelled in different stages of the contest to emerge the overall winner.`, <br />, <br />,  `Her words: In the first stage, there was a computer-based test, and we had to answer many questions in one hour. My score in the test was 66. The second stage took the same format, and I also scored 66.`, 'The quarter and semi-finals were on Microsoft Teams. We were asked questions, and we put in our answers; the first to put in the correct answers got 10 points.', <br />, <br />,  `Revealing how she prepared for the contest, Odunsi said she made sure the competition did not affect her academic activities. She had after-school lessons and also studied at night from 11 pm to 12 am. As the winner of the contest, Faith was presented with a cash prize of $1,000.`, <br />, <br />, 
       `Before winning the global contest, Faith had in 2018 set a record in Cowbellpedia by answering 19 questions in 60 seconds. See the link below.`] 
    },
  
    {
      id: 2,
      title: "Mikano Geely Assembly Plant Comes Alive in Ogun",
      Name: "Good News",
      Description: "In a move that would further boost local manufacturing and grow the economy, Mikano International, in collaboration with leading automobile maker Geely, has established an assembly plant in Nigeria. ",
      url: "https://res.cloudinary.com/dmsyfdo0y/image/upload/v1631574366/News%20Article%20Images/Business_and_Finance_1_h4q7ky.jpg",
  
      contents: "In a move that would further boost local manufacturing and grow the economy, Mikano International, in collaboration with leading automobile maker Geely, has established an assembly plant in Nigeria.  The Mikano Geely Motor Assembly Plant in Karameh City, Warewa, Lagos-Ibadan Expressway, Ogun State, will produce 400,000 cars annually, has an investment portfolio of N500 billion, and create thousands of jobs.      The modern factory will help meet the requirements and demands for a current car, producing 10,000 units of vehicles annually.  Geely owns Volvo Car Group and is the biggest shareholder of Daimler AG (to which Mercedes Benz belongs). This allows it to acquire the highest global and future technologies in the automotive industry.  Over the past 10 years, Geely has invested more than $14 billion in research and development (R&D) and plans to invest more in the next five years, in a commitment to providing the highest level of modern technologies in the industry and has recorded notable growth indexes. Explaining Mikano’s decision to venture into the automobile and its choice of Geely, Deputy Chief Executive Officer of Mikano International, Lokman Jouni, said it was in its interest and the common good. He said: “We have almost 2,800 staff, we have eight branches across Nigeria. We have over 400 service cars. Just imagine the number of our people – our staff on the road and the number of hours they spend on the road. Number one, the quality of cars we have here, especially second-hand vehicles, is not encouraging. Also, we tried some other brand-new cars, and it was equally disappointing. Again, out of over 1.4 million cars in the market, at least 1.2m is second-hand. Nigeria has become a dumping area for the whole world.” Jouni added: “We went to different auto shows in Beijing, Dubai, Europe. We visited other car manufacturers, and we found out that Geely can match these components. For safety purposes, Geely owns 100 per cent of the Volvo Group. So, the technology and the durability have been transferred to Geely. Then you need a car that is beautiful and elegant for people. Geely owns 10 per cent of Daimler AG – the owner of Mercedes-Benz. So, we have elegance. It is not fancy, it is beautiful, it is acceptable, it is smooth. Then we went for the strongest engine – proton. Proton is one of the highest efficient engines in the world. If you combine all these, you get a good, durable, smooth, solid car. Above all, this car was imported into Nigeria during the pandemic by air. We did well over 30,000km from Lagos to Calabar, Lagos-Kano, and other parts of the country.   “We tested the car and found out it is good for Nigeria, and that was why we brought it. The car fits the Nigerian and African environment in terms of weather and fuel quality. So, in terms of height, air condition, technology, and price, it meets all requirements. It is not very cheap and at the same time not too expensive.”     "
    },
  
    {
      id: 3,
      title: "Ikorodu Bois appear on Times Square’s Billboard  ",
      Name: "Good News",
      Description: "The Ikorodu Bois have featured on a Netflix advert displayed on Broadway Times Square, New York City.  ",
      url: "https://res.cloudinary.com/dmsyfdo0y/image/upload/v1631574366/News%20Article%20Images/Business_and_Finance_1_h4q7ky.jpg",
  
      contents: "  The Ikorodu Bois have featured on a Netflix advert displayed on Broadway Times Square, New York City.     The young internet sensations joined A-list celebrities including Burna Boy, Wizkid, Tiwa Savage, and Davido, who had featured on a billboard in Times Square.          The Times Square in Mid-Manhattan is a major tourist destination and entertainment center in New York.    A clip of a trailer remade by the Ikorodu Bois was included in the advert.    This is another feat for the group consisting of Muiz Sanni (15), Malik Sanni (10), and Fawas (13).    The group is known for remaking, mimicking, and recreating multimillion-dollar music videos, movie scenes, and movie trailers using everyday household items.     Netflix recently disclosed plans to feature the boys in its Oscar Weekend Film Brand Campaign.         A statement from the company read in part, “Netflix’s wide reach has woken up a new generation of global film fans, allowing them to discover more diverse perspectives, see themselves reflected and inspiring new forms of movie-love.    “Once a year, the Oscars pierce the culture and put movies on our collective minds, and this year, we are putting the spotlight on the Ikorodu Bois to remind movie fans that fans are the most important part of the movies.”       "
    }
]